### ISSUE TITLE
是否有VUE版本分享？

### ISSUE THREAD

**Issue by nickliufc** [baidumapapi/DrawingManager#1]
您好，
最近在做地图相关应用，找到你们这个组件，
看了Demo，交互觉得效果很不错，用户体验比较好，很喜欢。
但苦于用的是VUE框架，一直没办法成功引入这个组件。

想请教下，你们是否有VUE版组件代码分享下？
万分感谢~

**Comment by hinikai** [comment]
没有单独的vue组件，建议结合这个百度地图的vue组件库使用https://github.com/Dafrok/vue-baidu-map
